const Type = {
  SET_TEST: 'SET_TEST',
  SHOW_WARNING: 'SHOW_WARNING',
  REMOVE_WARNING: 'REMOVE_WARNING',
  USER_AUTH: 'USER_AUTH',
  USER_DATA: 'USER_DATA',
  USER_PROFILE: 'USER_PROFILE',
  GET_CONTACTS: 'GET_CONTACTS',
  CHAGE_PAGE: 'CHAGE_PAGE',
  TOTAL_PAGE: 'TOTAL_PAGE',
  VIEW_PAGE: 'VIEW_PAGE',
  FILTRED_VIEW: 'FILTRED_VIEW',
  SET_ITEM: 'SET_ITEM',
  SET_ROW: 'SET_ROW',
  SORT_MALE: 'SORT_MALE',
  SORT_FEMALE: 'SORT_FEMALE',
  RESET_FILTER: 'RESET_FILTER',

};
export default Type;
